package com.dypiu.nba.emmu.dto;

public enum EmmuIntent {
    OUTCOME_ATTAINMENT,
    ROOT_CAUSE,
    COURSE_RANKING,
    COURSE_INTELLIGENCE,
    ATR_ACTION,
    ATR_INTELLIGENCE,
    HISTORICAL_TREND,
    PROGRAMME_LANDSCAPE,
    CONTEXT_SUMMARY,
    STUDENT_EVIDENCE,
    GENERIC_OBE,
    GENERIC_CHAT,
    MUTATION_ATTEMPT
}
