-- ============================================================
-- DYPIU NBA ATTAINMENT SYSTEM — MIGRATION V3
-- Hierarchical Deletion Request & Permanent Soft-Delete Schema
-- ============================================================

-- 1. Add Soft Delete Columns to Programme Batches
ALTER TABLE programme_batches ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE programme_batches ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);

-- 2. Add Soft Delete Columns to Programme Batch Courses
ALTER TABLE programme_batch_courses ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE programme_batch_courses ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);

-- 3. Create Deletion Requests Table
CREATE TABLE IF NOT EXISTS deletion_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type VARCHAR(100) NOT NULL,
    resource_id VARCHAR(255) NOT NULL,
    programme_batch_id VARCHAR(100),
    programme_batch_course_id VARCHAR(100),
    master_programme_id VARCHAR(100),
    department_id VARCHAR(100),
    school_id VARCHAR(100),
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    requested_by VARCHAR(255),
    requested_by_id VARCHAR(100),
    requested_by_role VARCHAR(50),
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_by VARCHAR(255),
    reviewed_by_id VARCHAR(100),
    reviewed_by_role VARCHAR(50),
    reviewed_at TIMESTAMP WITH TIME ZONE,
    executed_at TIMESTAMP WITH TIME ZONE,
    remarks TEXT,
    rejection_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 4. Indexes for Fast Workflow Lookup and Scoping
CREATE INDEX IF NOT EXISTS idx_deletion_requests_resource ON deletion_requests(resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_deletion_requests_status ON deletion_requests(status);
CREATE INDEX IF NOT EXISTS idx_deletion_requests_scope ON deletion_requests(school_id, department_id, master_programme_id);
CREATE INDEX IF NOT EXISTS idx_programme_batches_deleted ON programme_batches(deleted_at);
CREATE INDEX IF NOT EXISTS idx_programme_batch_courses_deleted ON programme_batch_courses(deleted_at);
