import re

with open('/Users/rajshaikh/Desktop/DYPIU-NBA-Attainment-backend/obe-backend/src/main/java/com/dypiu/nba/service/AttainmentReportService.java', 'r') as f:
    text = f.read()

text = re.sub(r'        \}\n        if \(calcResult\.getAverageMapping\(\) != null && calcResult\.getAverageMapping\(\)\.getPsos\(\) != null\) \{\n            for \(ProgrammeAttainmentResultDto\.OutcomeMappingItem item : calcResult\.getAverageMapping\(\)\.getPsos\(\)\) \{\n                report1\.add\(ProgrammeBatchAttainmentReportDto\.Report1Row\.builder\(\)\n                        \.psoCode\(item\.getOutcomeCode\(\)\)\n                        \.semesterAverages\(item\.getSemesterAverages\(\)\.stream\(\)\n                                \.map\(s -> new ProgrammeBatchAttainmentReportDto\.SemesterContribution\(s\.getSemester\(\), s\.getAverage\(\)\)\)\n                                \.collect\(Collectors\.toList\(\)\)\)\n                        \.programmeAverageMapping\(item\.getProgrammeAverage\(\)\)\n                        \.build\(\)\);\n            \}\n        \}', '', text, flags=re.DOTALL)

text = re.sub(r'        \}\n        if \(calcResult\.getAverageDirectAttainment\(\) != null && calcResult\.getAverageDirectAttainment\(\)\.getPsos\(\) != null\) \{\n            for \(ProgrammeAttainmentResultDto\.OutcomeDirectItem item : calcResult\.getAverageDirectAttainment\(\)\.getPsos\(\)\) \{\n                report2\.add\(ProgrammeBatchAttainmentReportDto\.Report2Row\.builder\(\)\n                        \.psoCode\(item\.getOutcomeCode\(\)\)\n                        \.semesterDirectAttainments\(item\.getSemesterAverages\(\)\.stream\(\)\n                                \.map\(s -> new ProgrammeBatchAttainmentReportDto\.SemesterContribution\(s\.getSemester\(\), s\.getAverage\(\)\)\)\n                                \.collect\(Collectors\.toList\(\)\)\)\n                        \.programmeDirectAttainment\(item\.getProgrammeAverage\(\)\)\n                        \.build\(\)\);\n            \}\n        \}', '', text, flags=re.DOTALL)

text = re.sub(r'List<ProgrammeBatchAttainmentReportDto\.Report3Row> report3 = new ArrayList\<\>\(\);\n        if \(calcResult\.getAverageIndirectAttainment\(\) != null\) \{\n            for \(Map\.Entry<String, BigDecimal> entry : calcResult\.getAverageIndirectAttainment\(\)\.entrySet\(\)\) \{\n                String code = entry\.getKey\(\);\n                BigDecimal indirect = entry\.getValue\(\);\n                ProgrammeBatchAttainmentReportDto\.Report3Row row = ProgrammeBatchAttainmentReportDto\.Report3Row\.builder\(\)\n                        \.percentageSubstantial\(BigDecimal\.ZERO\)\n                        \.percentageModerate\(BigDecimal\.ZERO\)\n                        \.percentageSlight\(BigDecimal\.ZERO\)\n                        \.weightedScore\(BigDecimal\.ZERO\)\n                        \.indirectPercentage\(indirect\)\n                        \.indirectAttainmentLevel\(indirect\)\n                        \.build\(\);\n                if \(code\.startsWith\("PO"\)\) row\.setPoCode\(code\);\n                else row\.setPsoCode\(code\);\n                report3\.add\(row\);\n            \}\n        \}', '', text, flags=re.DOTALL)


text = re.sub(r'List<ProgrammeBatchAttainmentReportDto\.Report4Row> report4 = new ArrayList\<\>\(\);\n        BigDecimal sumOverall = BigDecimal\.ZERO;\n        int countOverall = 0;\n\n        if \(calcResult\.getOverallAttainment\(\) != null && calcResult\.getOverallAttainment\(\)\.getPos\(\) != null\) \{\n            for \(ProgrammeAttainmentResultDto\.OutcomeAttainmentItem item : calcResult\.getOverallAttainment\(\)\.getPos\(\)\) \{\n                report4\.add\(ProgrammeBatchAttainmentReportDto\.Report4Row\.builder\(\)\n                        \.poCode\(item\.getOutcomeCode\(\)\)\n                        \.targetLevel\(item\.getTargetLevel\(\)\)\n                        \.directAttainment\(item\.getDirectAttainment\(\)\)\n                        \.indirectAttainment\(item\.getIndirectAttainment\(\)\)\n                        \.finalAttainment\(item\.getFinalAttainment\(\)\)\n                        \.targetMet\(item\.getTargetMet\(\)\)\n                        \.build\(\)\);\n                sumOverall = sumOverall\.add\(item\.getFinalAttainment\(\) != null \? item\.getFinalAttainment\(\) : BigDecimal\.ZERO\);\n                countOverall\+\+;\n            \}\n        \}\n        if \(calcResult\.getOverallAttainment\(\) != null && calcResult\.getOverallAttainment\(\)\.getPsos\(\) != null\) \{\n            for \(ProgrammeAttainmentResultDto\.OutcomeAttainmentItem item : calcResult\.getOverallAttainment\(\)\.getPsos\(\)\) \{\n                report4\.add\(ProgrammeBatchAttainmentReportDto\.Report4Row\.builder\(\)\n                        \.psoCode\(item\.getOutcomeCode\(\)\)\n                        \.targetLevel\(item\.getTargetLevel\(\)\)\n                        \.directAttainment\(item\.getDirectAttainment\(\)\)\n                        \.indirectAttainment\(item\.getIndirectAttainment\(\)\)\n                        \.finalAttainment\(item\.getFinalAttainment\(\)\)\n                        \.targetMet\(item\.getTargetMet\(\)\)\n                        \.build\(\)\);\n                sumOverall = sumOverall\.add\(item\.getFinalAttainment\(\) != null \? item\.getFinalAttainment\(\) : BigDecimal\.ZERO\);\n                countOverall\+\+;\n            \}\n        \}', '', text, flags=re.DOTALL)

with open('/Users/rajshaikh/Desktop/DYPIU-NBA-Attainment-backend/obe-backend/src/main/java/com/dypiu/nba/service/AttainmentReportService.java', 'w') as f:
    f.write(text)

