package com.dypiu.nba.reports.model;

public enum ReportType {
    COURSE_ATR,
    PROGRAMME_ATR,
    COURSE_ATTAINMENT,
    PROGRAMME_ATTAINMENT,
    PROGRAMME_ATTAINMENT_MAPPING,
    PROGRAMME_ATTAINMENT_DIRECT,
    PROGRAMME_ATTAINMENT_INDIRECT,
    PROGRAMME_ATTAINMENT_OVERALL
}
