package com.dypiu.nba.audit;

public enum ResourceType {
    SCHOOL,
    DEPARTMENT,
    MASTER_PROGRAMME,
    PROGRAMME_BATCH,
    MASTER_COURSE,
    PROGRAMME_BATCH_COURSE,
    PROGRAMME_OUTCOME,
    PROGRAMME_SPECIFIC_OUTCOME,
    PEO_OUTCOME,
    COURSE_OUTCOME,
    CO_PO_MAPPING,
    CO_PSO_MAPPING,
    ATTAINMENT_CONFIGURATION,
    DIRECT_ASSESSMENT,
    INDIRECT_ASSESSMENT,
    COURSE_ATTAINMENT,
    PROGRAMME_ATTAINMENT,
    COURSE_ATR,
    PROGRAMME_ATR,
    APPROVAL_REQUEST,
    DELETION_REQUEST,
    USER,
    ROLE_ASSIGNMENT
}
